### ISSUE TITLE
Compile on Raspian

### ISSUE THREAD

**Issue by namluap** [amurzeau/waveOverUDP#1]
Hello,

I would like to compile this project on Raspbian. I downloaded the zip file into a folder and extract it and have run Cmake-gui to generate the executables in a new folder, but it is not making the executables. No errors are displayed in cmake. I only get a bunch of files in the new folder with cmake files

Is it suitable for a Raspberry Pi? What am I doing wrong.
Sorry for the noob questions.

**Comment by amurzeau** [comment]
cmake-gui only generate a project, but doesn't do the actual build.

On the command line, from a fresh cloned repo you can do:
```sh
mkdir build
cd build
cmake ..
cmake --build .
```
cmake-gui only does the  `cmake ..` part.
You can do `cmake --build .` inside the build directory of cmake-gui.

**Comment by namluap** [comment]
Thanks, that helped a lot. 

Now when I'm running the program wavplayudp I get the following:

Warning: received datagram of size 427 but chunk size is 4

what to do?

**Comment by amurzeau** [comment]
That means wavePlayUDP received a UDP message with 427 bytes.
This is invalid as wavePlayUDP expect datagrams with 16 bits little endian sample format.

427 is not a multiple of 2 so it is not the expected 16 bits format.
Ensure the data sent to wavePlayUDP has the correct format.
