### ISSUE TITLE
The application waveSendUDP.exe compiled for Windows closes immediately after the start

### ISSUE THREAD

**Issue by miclast** [amurzeau/waveOverUDP#2]
The application compiled for Windows closes immediately after the start.

I use this string:
waveSendUDP.exe --chunksize 128 --chunknum 4 --device hw:0,0 --channel 2 --port 2305 192.168.1.47

Same issue using 32 and 64 bit compiled using Microsoft Visual Studio 2017.

wavePlayUDP.exe --chunksize 128 --chunknum 10 --device default --rate 48000 --channel 2 --port 2305 works fine.

**Comment by amurzeau** [comment]
if you launch it with the command line interpreter, what are the logs ?

**Comment by miclast** [comment]
C:\Users\user\Documents\Projects\waveOverUDP-master-bin\Debug>waveSendUDP.exe --chunksize 128 --chunknum 4 --device hw:0,0 --channel 2 --port 2305 192.168.1.47
Connecting to: 192.168.1.47:2305
Using default playback device

C:\Users\user\Documents\Projects\waveOverUDP-master-bin\Debug>

**Comment by sauer-m** [comment]
Same here...

**Comment by amurzeau** [comment]
I can't reproduce the issue, maybe its related to OS changes ? I use Windows 8.1.

Debug it inside visual studio to find what's wrong.
