### ISSUE TITLE
No audio in my output

### ISSUE THREAD

**Issue by ayoubnfh** [amurzeau/waveOverUDP#4]
hi,
i want to use your solution, i get the binanry files, when i try to use the commands for sending and playing audio over ip, i can't hear anything from my output, i check with wireshare, i found that the packets are sent successfully.
i already test to change the parametres with the option --device, but still same problem i hope that you can help with this problem.

**Comment by amurzeau** [comment]
does `aplay -D <device> file.wav` works with the same device ?

**Comment by ayoubnfh** [comment]
Yes the aplay works for me, 
the wavePlayUDP display the "Ready" part and not continue, seems it stucks with select command for me,

**Comment by amurzeau** [comment]
If you don't have "Playing" message in wavePlayUDP, then it is not received data from the socket. Ensure the port configured is the same for both and that there is no iptable or anything that would filter out packets at receive side (wavePlayUDP side).

**Comment by ayoubnfh** [comment]
Thanks a lot ! the iptable was the problem.
